### ISSUE TITLE
[BUG] Error decoding response in release 1.1.8-1

### ISSUE THREAD

**Issue by kgroshert** [graphite-project/docker-graphite-statsd#174]
**Describe the bug**

I don't know which of the components of the docker images might be at fault.
I'd appreciate a hint and open an issue in the corresponding repo if applicable.

I'm using a clustered graphite setup like this:

Grafana -> Graphite-web(frontend) -> 2*Graphite-web(whisper-files are here)

This frontend-graphite has this variable set:

GRAPHITE_CLUSTER_SERVERS="http://graphite01:80,http://graphite02:80"

So far I've been running the docker image release 1.1.7-8, which worked fine.
I have now updated the docker image of graphite02 to 1.1.8-1 and are now getting errors
during find_nodes, but I suspect only as I get to the end of the path where the whisper-files reside (see logs).

Logs from the frontend-graphite-web container when browsing higher up in the path (works fine):

`2021-07-16,06:21:29.614 :: graphite.finders.remote.find_nodes :: host: graphite02:80, query: <FindQuery: carbon_*.agents.*.* from * until *> 0.128553s
2021-07-16,06:21:29.614 :: graphite.finders.remote.find_nodes :: host: graphite01:80, query: <FindQuery: carbon_*.agents.*.* from * until *> 0.110915s
2021-07-16,06:21:29.730 :: find_view query=carbon_*.agents.*.* local_only=0 matches=53
2021-07-16,06:21:29.731 :: received remote find request: pattern=carbon_*.agents.*.* from=None until=None local_only=0 format=treejson matches=53
`

Logs from the frontend-graphite-web container at the end of the metrics path:

info.log:

`2021-07-16,06:09:15.942 :: graphite.finders.remote.find_nodes :: host: graphite01:80, query: <FindQuery: carbon_*.agents.*.tcp.* from * until *> 0.107724s
2021-07-16,06:09:16.001 :: graphite.finders.remote.find_nodes :: failed in 0.160645s
2021-07-16,06:09:16.001 :: Exception during find <FindQuery: carbon_*.agents.*.tcp.* from * until *> after 0.171643s: Error decoding response from http://graphite02:80
/metrics/find/?local=1&format=pickle&query=carbon_%2A.agents.%2A.tcp.%2A: 'Interval' object has no attribute '__dict__'
`

exception.log:

`2021-07-16,06:09:15.926 :: RemoteFinder[graphite02:80] Error decoding response from http://graphite02:80/metrics/find/?local=1&format=pickle&quer
y=carbon_%2A.agents.%2A.tcp.%2A: 'Interval' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 291, in deserialize
    return self._deserialize_stream(reader, result.getheader('content-type'))
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 319, in _deserialize_stream
    data = unpickle.load(stream)
  File "/opt/graphite/webapp/graphite/util.py", line 219, in load
    return SafeUnpickler(file).load()
AttributeError: 'Interval' object has no attribute '__dict__'
`

**To Reproduce**
Use Grafana explore to show metrics.
Upgrade a backend container to 1.1.8-1 breaks it. Downgrading to 1.1.7-8 fixes it.

**Expected behavior**
find_nodes should return data and the frontend-graphite should understand the reply

**Environment (please complete the following information):**
 - OS flavor: Suse Linux Enterprise 12
 - Image version 1.1.7-8 and 1.1.8-1
 - Variables used: GOCARBON=1, GRAPHITE_CLUSTER_SERVERS="http://graphite01:80,http://graphite02:80"

**Comment by deniszh** [comment]
Hmmm... I think it's caused by https://github.com/graphite-project/graphite-web/pull/2693 but not sure why. Are you sure that you upgraded both versions? Probably after #2693 1.1.8 can't talk with previous versions. Will try to reproduce but I'm AFK now, only can test that in a week or so...

**Comment by deniszh** [comment]
PS: or you can try msg pack serialization - GRAPHITE_CLUSTER_SERVERS="http://graphite01:80?format=msgpack,http://graphite02:80?format=msgpack"

**Comment by kgroshert** [comment]
To clarify: The frontend is 1.1.8-1. It will not talk to the 1.1.8-1 backend but to the 1.1.7-8 backend without problems.
No hurry, I downgraded all backends to 1.1.7-8 so it will work for now.
I will try msgpack with 1.1.8-1 and report back.

**Comment by kgroshert** [comment]
I now put "format=msgpack" in the GRAPHITE_CLUSTER_SERVERS variable for the backends and updated them to 1.1.8-1 again. Now it works without problems. Let me know if you need any debug-output.

**Comment by deniszh** [comment]
Well, incompatibility between 1.1.8 and version below is kinda expected, as I found. But msgpack should fix that, indeed.
